apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-react
  labels:
    app: hello-world-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-react
  template:
    metadata:
      labels:
        app: hello-world-react
    spec:
      containers:
      - name: hello-world-react
        image: arjun7443/ultimate-cicd:replaceImageTag
        ports:
        - containerPort: 8080
