apiVersion: v1
kind: Service
metadata:
  name: hello-world-react-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-world-react
